# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Reign' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-recruiting-hsa

  pod 'Moya', '~> 13.0'

  target 'ReignTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReignUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
